"""create companies and interview_rounds tables

Revision ID: 0d6b5531c420
Revises: 
Create Date: 2026-07-06 13:40:15.545390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d6b5531c420'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role_title', sa.String(), nullable=False),
    sa.Column('applied_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('APPLIED', 'IN_PROGRESS', 'OFFER', 'REJECTED', 'GHOSTED', name='companystatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.create_table('interview_rounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('round_type', sa.Enum('OA', 'PHONE_SCREEN', 'TECHNICAL', 'SYSTEM_DESIGN', 'HR', 'ONSITE', name='roundtype'), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'PASSED', 'FAILED', 'PENDING', name='roundstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_rounds_id'), 'interview_rounds', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f('ix_interview_rounds_id'), table_name='interview_rounds')
    op.drop_table('interview_rounds')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_table('companies')

    # Postgres does not drop ENUM types when a table using them is dropped.
    # Without this, a second upgrade after this downgrade fails with
    # "type already exists". Drop in reverse dependency order.
    op.execute('DROP TYPE IF EXISTS roundstatus')
    op.execute('DROP TYPE IF EXISTS roundtype')
    op.execute('DROP TYPE IF EXISTS companystatus')
