"""add deleted_at to companies for soft delete

Revision ID: ac9a0ede6b6f
Revises: 0d6b5531c420
Create Date: 2026-07-09 01:58:40.784456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac9a0ede6b6f'
down_revision: Union[str, Sequence[str], None] = '0d6b5531c420'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'deleted_at')
    # ### end Alembic commands ###
